### ISSUE TITLE
Multiply two strings

### ISSUE THREAD

**Issue by amartya-k** [amartya-k/Recursive-Algorithm#34]
Write a program to multiply two strings. 
Eg: 
```
string1 = "12" 
string2 = "5"
Output = "60"
```
Input size can by anything(might exceed unsigned long long int if using c++). 
Any other languages please try to do it without using inbuilt methods. 
Hint: _Represent the number as array._

**Comment by omarahmed1111** [comment]
I would like to implement this in c++

**Comment by NandiniMundra-8** [comment]
hey @amartya-k ,I would love to perform this task in C or C++,can you assign this to me  ?

**Comment by ghanender-chauhan** [comment]
I want to do complete this issue
 . I will do this in python

**Comment by amartya-k** [comment]
> I would like to implement this in c++

Go for it. You have been assigned.

**Comment by ayoolafelix** [comment]
Hey @amartya-k  , I would love to perform this task in Python, can you assign this to me?

**Comment by leli-1** [comment]
Can you assign this to me for python ?

**Comment by rcoder23** [comment]
I want to work in this issue . Language Java

**Comment by amartya-k** [comment]
Good work everyone. 👍
